# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d22adb9b4fd041f6e5775d1b5b03bcb5ee64bdf325e983df4cd3feb85e35c85052f3202ed92ec9b5e07023f498e4c60a043afd86b82452dc0b5114a525759d6d

test:
  secret_key_base: 5f37f1e6938082f4580652ed4515d4dedaeddc891b8fbae4d517fc9bddc30fd11f0d2023fe362cfa19fd9184a5c108b8dae3521692c0c0d1b755721f8e3ba0c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
